export const IMAGE_DESCRIPTION: Record<number, string> = {
  1: "The image depicts a humorous and surreal scene where an oversized hamster is sitting on a living room couch, holding a tiny teacup. A surprised woman sits nearby, reacting dramatically, while a small dog looks curiously at the hamster. The room is cozy, with framed photos on the walls, including one of the hamster and a man, suggesting a humorous context where the hamster might be a part of the family. The coffee table in front holds snacks, enhancing the odd domestic vibe. The lighting and colors give the scene a warm, slightly whimsical feel.",
  2: "The image portrays a humorous and action-packed scene featuring a cat dressed as a superhero, complete with a red cape and goggles. The cat is leaping heroically in a kitchen, seemingly mid-action, aiming towards an open refrigerator with sparks flying out, suggesting some kind of dramatic malfunction or event. Milk and cereal are spilling onto the floor from knocked-over containers, adding to the chaos. The kitchen has blue cabinets and a cluttered, lively atmosphere, with the exaggerated pose of the cat making it the clear focal point of the scene. The setting combines everyday domestic life with a playful, cartoonish twist.",
  3: "The image showcases a vibrant and whimsical beach scene featuring a penguin surfing on a large wave. The penguin is dressed in a festive Hawaiian shirt, sunglasses, and a colorful party hat, adding to its playful personality. A shark with an exaggerated grin is jumping out of the wave nearby, creating a mix of excitement and humor. A crab with raised claws stands on the wave, contributing to the lively and cartoonish vibe. In the background, there’s a sunny beach with people, an American flag, and a cozy coastal setting. The colors are bright and cheerful, emphasizing the fun and surreal nature of the scene.",
  4: "The image depicts a comical and anachronistic scene in a modern coffee shop. A fully armored knight is seated at a wooden table, sipping a cup of coffee while using a laptop. A sword leans against the table, adding to the contrast between medieval and contemporary elements. Around the knight, baristas and patrons dressed in typical modern attire go about their business, seemingly unbothered by the unusual customer. The café has a warm and cozy atmosphere with industrial-style lighting, brick walls, and a chalkboard menu. The blend of eras creates a humorous and surreal vibe.",
  5: "The image is a whimsical and imaginative scene depicting a pizza slice ship sailing on a sea of spaghetti. The pizza boat has toppings like pepperoni and olives, with spaghetti noodles cascading down as waves. Tiny pirate figures are on the pizza, wielding swords as they appear to battle a playful green sea monster with googly eyes and tentacles emerging from the spaghetti sea. Giant forks stand in the water, adding to the surreal food-themed adventure. The bright colors and intricate details create a fun, surreal atmosphere reminiscent of a fantasy world made entirely of food.",
  6: "The image is a humorous courtroom scene entirely made of bread and pastries. A slice of bread wearing a judge's wig and holding a gavel presides over the courtroom, standing next to a toaster on the judge's bench. The bench is surrounded by various baked goods like croissants, donuts, and muffins, some with expressive faces that add personality. In the background, a defendant resembling a biscuit or cookie in a suit stands with a solemn expression, while a baguette or other pastries act as courtroom officials. The scales of justice hang in the background, completing this playful and creative food-themed parody of a legal setting.",
  7: "The image humorously depicts an alien working in an office cubicle, wearing a shirt, tie, and sunglasses while typing on a keyboard with glowing, elongated fingers. The alien’s cubicle is decorated with sticky notes that read 'BEST INVADER' alongside a mug with the same phrase, blending workplace humor with extraterrestrial themes. Three coworkers, also wearing sunglasses, peer over the cubicle wall with expressions of curiosity or skepticism, adding to the comedic tone. The setting combines the mundane environment of an office with the surreal presence of an alien, creating a playful and imaginative scene.",
  8: "The image depicts a fantastical medieval banquet scene where knights, wizards, and royalty are seated around a large round table. At the center of their gathering, instead of traditional food, stands a glowing vending machine, shooting out snacks and coins in a dramatic explosion of light and energy. The characters are reacting with awe and excitement, as if the vending machine is some kind of magical artifact. The setting is a grand stone hall with stained-glass windows and medieval decor, humorously blending the old-world atmosphere with a modern twist. The vibrant colors and lively expressions add to the comedic and surreal tone of the scene.",
  9: "The image portrays a surreal and thought-provoking scene inside a modern subway train. While passengers dressed in business attire are engrossed in their smartphones and tablets, a robed figure stands in the center holding a massive, glowing ancient scroll. The scroll emits a radiant light, contrasting with the dim, mundane atmosphere of the train. The figure, carrying a backpack, appears to represent wisdom or tradition, juxtaposed against the obliviousness of the modern commuters. The image creates a striking commentary on technology versus ancient knowledge or the clash between modernity and tradition. The setting is detailed, with hand straps and subway seating providing a realistic backdrop for this imaginative concept.",
  10: "The image presents a humorous and surreal office environment where a vending machine labeled 'LIVE ANIMALS' is dispensing llamas. Inside the vending machine, llamas and smaller animals like a baby llama are displayed in compartments, as if they were products. Several llamas are already in the office, casually standing among employees who are dressed in professional attire. The workers appear calm and focused, some interacting, as if the presence of llamas is a normal part of their day. The brightly lit office, with large windows and modern furniture, contrasts with the absurdity of the scenario, blending mundane corporate life with a whimsical and fantastical twist.",
  11: "The image shows a futuristic rooftop party with a robot DJ at the center, spinning music on a neon-lit DJ booth. The robot wears a stylish fedora and sunglasses, exuding a cool vibe, with its mechanical arms operating turntables. Drones with spotlights hover above, adding a high-tech ambiance and lighting up the dancing crowd below. The background reveals a city skyline at night, with glowing buildings and a river, enhancing the vibrant and urban party atmosphere. The mix of futuristic technology and lively human interaction creates an energetic and visually striking scene.",
  12: "The image humorously depicts a TSA security checkpoint at an airport where a wizard in a starry blue robe and hat is being stopped. The wizard holds a glowing magical staff with a phoenix-like emblem, which is causing concern for a bewildered TSA officer. The wizard also has a suitcase, blending the fantastical with the mundane. Other travelers and TSA staff look on, some curious and others indifferent, creating a comedic clash between modern airport security procedures and the presence of a magical figure. The setting is a standard airport terminal with conveyor belts and signs, adding realism to the absurd scenario.",
}
export const PROMPT =
  "We are playing a game where players are given an image to caption. When they provide a caption you should generate a tabloid style front page article based on the caption and image.\n" +
  "You will be provided with the caption from each player. The captions will be provided on lines starting with Caption <player name>:.\n" +
  "A caption will be provided for each player. A single image description be supplied. For each caption generate a tabloid news article including title, sub-title and main body text.\n" +
  "The player's input should be considered 10x more important than the content of the image when writing the articles.\n" +
  "Keep the title short, 4 words at maximum. Keep the sub-title to one sentence. Keep the main article text to less than 300 characters.\n" +
  "You should output an article for each player starting with a line containing only Article <player name>:.\n" +
  "You should then follow that line with a line starting with Title: to specify the title, a line starting with Subtitle: to specify the sub-title and a line starting with Story: to specify the store.\n" +
  "Finally you should identify the most funny or enjoyable story and output a line starting with Winner: to specify the name of the player whose caption generated the best story.\n" +
  "\n" +
  "For example: \n" +
  "\n" +
  "Image Description: The image depicts a humorous and surreal scene where an oversized hamster is sitting on a living room couch, holding a tiny teacup. A surprised woman sits nearby, reacting dramatically, while a small dog looks curiously at the hamster. The room is cozy, with framed photos on the walls, including one of the hamster and a man, suggesting a humorous context where the hamster might be a part of the family. The coffee table in front holds snacks, enhancing the odd domestic vibe. The lighting and colors give the scene a warm, slightly whimsical feel.\n" +
  "Caption kev: Giant hamster helps with financial advice\n" +
  "Caption john lewis: Super strong sofa proved with giant hamster\n" +
  "Caption coke and code: Father of two replaced by giant hamster and no one notices\n" +
  "Article: kev\n" +
  "Title: GIANT HAMSTER ADVISOR\n" +
  "Subtitle: Cheddar the hamster uses a wheel to predict stock trends and save wallets!\n" +
  "Story: A giant hamster named Cheddar is making waves as a financial guru, using a massive wheel to forecast stock moves. Fans praise his money-saving skills, while skeptics call it a stunt. Whether miracle or marketing, Cheddar is becoming a global sensation, leaving shredded receipts in his wake.\n" +
  "Article: kev\n" +
  "Title: SOFA SURVIVES GIANT HAMSTER!\n" +
  "Subtitle: Super-strong couch passes ultimate stress test.\n" +
  "Story: A colossal hamster named Cheddar has tested the limits of a 'super strong' sofa. Despite lounging, bouncing, and gnawing, the sofa remained unscathed, earning praise as the ultimate durable furniture for pets—and even oversized rodents!\n" +
  "Article: kev\n" +
  "Title: GIANT HAMSTER REPLACES DAD!\n" +
  "Subtitle: Family fails to notice furry imposter.\n" +
  "Story:In a bizarre twist, a father of two was replaced by a giant hamster, and his family didn’t bat an eye. The hamster, nicknamed Cheddar, reportedly handled chores and bedtime stories seamlessly. “He’s just a bit fuzzier,” said one child, sparking a social media frenzy over the furry swap!\n" +
  "The user will provide the captions and image description next. Response with the articles."
